[package]
name = "newgen"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"
authors = ["Víctor Mardones vmardones.dev@gmail.com"]
readme = "README.md"
keywords = ["builder", "macro", "derive", "constructor"]
categories = ["rust-patterns"]
repository = "https://github.com/AnotherGoat/newgen"
description = "Customizable constructor generation for structs and enums"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.117", features = ["full"] }
quote = "1.0.44"
proc-macro2 = "1.0.106"
heck = "0.5.0"

[dev-dependencies]
trybuild = "1.0.116"

[features]
default = ["std"]
std = []
public-default = []

[workspace]
members = ["fail_crate"]
